### ISSUE TITLE
Typedef the structs

### ISSUE THREAD

**Issue by Qu3tzal** [MaxenceRobin/Teutates#1]
For the structures, quality of life improvement would be to define the structure with a name like `struct X_` and then `typedef struct X_ X;` to get rid of the `struct` when using the structure as a user.

For instance here:
https://github.com/MaxenceRobin/Teutates/blob/29ee624170ff945e7f5eafca2ae6498c0c30f7bd/include/teutates.h#L79

It would become:
```c
struct teutates_test_ {
	const char *name;
	teutates_test_cb test;
};
typedef struct teutates_test_ teutates_test;
```
```c
// Now we can use directly teutates_test
teutates_test *result;
```

**Comment by MaxenceRobin** [comment]
This has been done on purpose, as this project use the linux kernel coding style (https://www.kernel.org/doc/html/v4.10/process/coding-style.html), and this coding style forbids the use of typedef for structures.
